name: Build, Test, and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/enterprise-ai-poc

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker build
        run: |
          docker build -t ai-poc-img .

  push-image:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: meta
        run: |
          echo "tag=${{ env.IMAGE_NAME }}:${{ github.sha }}" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tag }}
            ${{ env.IMAGE_NAME }}:latest


  deploy:
    needs: push-image
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/enterprise-ai-poc:${{ github.sha }}"

            echo "Pulling image: $IMAGE"
            docker pull "$IMAGE"

            echo "Stopping old container..."
            docker stop enterprise-ai-poc || true

            echo "Removing old container..."
            docker rm enterprise-ai-poc || true

            echo "Starting new container..."
            docker run -d \
              --name enterprise-ai-poc \
              --restart unless-stopped \
              -p 8501:8501 \
              "$IMAGE"

            echo "Deployment completed."

            docker ps   
