name: Enterprise AI POC CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu:latest 
    steps:
      - uses: actions/checkout@v4

      - name: Docker build
        run: docker build -t ai-poc-img .

  push-image:
    needs: build
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
  deploy:
    needs: push-image
    runs-on: ubuntu-latest
    steps:
      - name: deploying  
        script:
         docker pull ai-poc-img 
         docker run -d \
            --name enterprise-ai-poc \
            --restart unless-stopped \
            -p 8501:8501 container1 ai-poc-img

